so ~/.vim/configs/plugins/airline.vim
so ~/.vim/configs/plugins/bufexplorer.vim
so ~/.vim/configs/plugins/choosewin.vim
so ~/.vim/configs/plugins/colortuner.vim
so ~/.vim/configs/plugins/commandt.vim
so ~/.vim/configs/plugins/ctrlp.vim
so ~/.vim/configs/plugins/easymotion.vim
so ~/.vim/configs/plugins/easytags.vim
so ~/.vim/configs/plugins/indentline.vim
so ~/.vim/configs/plugins/matchtagalways.vim
so ~/.vim/configs/plugins/mirror.vim
so ~/.vim/configs/plugins/multiple-cursor.vim
so ~/.vim/configs/plugins/nerdtree.vim
so ~/.vim/configs/plugins/numbers.vim
so ~/.vim/configs/plugins/pathogen.vim
so ~/.vim/configs/plugins/ruby-matchit.vim
so ~/.vim/configs/plugins/smartgf.vim
so ~/.vim/configs/plugins/sparkup.vim
so ~/.vim/configs/plugins/startify.vim
so ~/.vim/configs/plugins/syntastic.vim
so ~/.vim/configs/plugins/tabularize.vim
so ~/.vim/configs/plugins/ultisnips.vim
so ~/.vim/configs/plugins/vimshell.vim
so ~/.vim/configs/plugins/visual-increment.vim
so ~/.vim/configs/plugins/vim-better-javascript-completion.vim
so ~/.vim/configs/plugins/vim-jsdoc.vim
so ~/.vim/configs/plugins/vim-jsx.vim

